stream {
    include /etc/nginx/snippets/ruconet-stream.conf;

    # PostgreSQL
    server {
        listen db.ruconet.internal:5432 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        proxy_pass 127.0.0.1:5432;
        proxy_timeout 12h;
    }
}
